version: '3.1'

services:
  app:
    container_name: chilflix-backend
    build: .
    command: npm run dev
    ports:
      - '4000:4000'
    links:
      - mongo
    volumes:
      - ./:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ''
      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
volumes:
  mongodb:
    driver: local
